name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@9aa53726e4600b4a502939fdc4e59ba4a2949153 # v1.2.1
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
