name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@aa3b9a86d8f9ad0755301291b4a000581a4b97b1 # v1.11.12
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
